# Group Contacts

## Register [/api/contacts]
### Create an Entity [POST]
+ Request
    + Headers
            Content-Type: application/json
    + Body
            {
                "type": "email",
                "contact": "linda@ushahidi.com",
                "can_receive": "1"
            }

+ Response 201

## Find [/api/contacts/{id}]
### Show a contact details [GET]
+ Request
    + Headers
            Authorization Bearer 
            Content-Type: application/json

+ Response 200 (application/json)
    + Body
            {
                "data": {
                    "type": "email",
                    "contact": "linda@ushahidi.com",
                    "can_receive": "1",
                    "user_id": "3",
                    "created_at": "2016-03-30 16:11:36",
                    "updated_at": "2016-03-30 16:11:36"
                }
            }

## Update [/api/contacts/{id}]
### Update a contact's details [PUT]
+ Request
    + Headers
            Authoriation Bearer 
            Content-Type: application/json
    +Body
            {
                "data": {
                    "type": "phonenumber",
                    "contact": "0721674180",
                    "can_receive": "1",
                    "user_id": "NULL"	
                }
            }
+ Response 200 (application/json)
    + Body
            {
                "data": {
                    "id": 3
                    "type": "phonenumber",
                    "contact": "0721674180",
                    "can_receive": "1",  
                    "user_id": "NULL", 
                    "created_at": "2016-03-30 16:11:36",
                    "updated_at": "2016-03-30 16:11:36"
                }
            }
