# Group Organizations

## Register [/api/organizations]
### Create an Entity [POST]
+ Request
    + Headers
            Content-Type: application/json
    + Body
            {
                "name": "Ushahidi",
                "url": "ushahidi@rollcall.io"
            }

+ Response 201

## Find [/api/organizations/{id}]
### Show an organization details [GET]
+ Request
    + Headers
            Authorization Bearer 
            Content-Type: application/json

+ Response 200 (application/json)
    + Body
            {
                "data": {
                    "name": "Ushahidi",
                    "url": "ushahidi.rollcall.io",
                    "created_at": "2016-03-30 16:11:36",
                    "updated_at": "2016-03-30 16:11:36"
                }
            }

## Update [/api/organizations/{id}]
### Update an organization's details [PUT]
+ Request
    + Headers
            Authoriation Bearer 
            Content-Type: application/json
    +Body
            {
                "data": {
                    "name": "RollCall Inc",
                    "url": "rollcall@rollcall.io"	
                }
            }
+ Response 200 (application/json)
    + Body
            {
                "data": {
                    "id": 3
                    "name": "RollCall Inc",
                    "url": "rollcall@rollcall.io"   
                    "created_at": "2016-03-30 16:11:36",
                    "updated_at": "2016-03-30 16:11:36"
                }
            }